// Code generated by mockery v2.14.0. DO NOT EDIT.

package mock

import (
	di "github.com/gozix/di"

	mock "github.com/stretchr/testify/mock"
)

// BundleDependsOn is an autogenerated mock type for the BundleDependsOn type
type BundleDependsOn struct {
	mock.Mock
}

// Build provides a mock function with given fields: builder
func (_m *BundleDependsOn) Build(builder di.Builder) error {
	ret := _m.Called(builder)

	var r0 error
	if rf, ok := ret.Get(0).(func(di.Builder) error); ok {
		r0 = rf(builder)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DependsOn provides a mock function with given fields:
func (_m *BundleDependsOn) DependsOn() []string {
	ret := _m.Called()

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// Name provides a mock function with given fields:
func (_m *BundleDependsOn) Name() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

type mockConstructorTestingTNewBundleDependsOn interface {
	mock.TestingT
	Cleanup(func())
}

// NewBundleDependsOn creates a new instance of BundleDependsOn. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewBundleDependsOn(t mockConstructorTestingTNewBundleDependsOn) *BundleDependsOn {
	mock := &BundleDependsOn{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
